# ===== Stage 1: Serve static frontend =====
FROM nginx:alpine

WORKDIR /usr/share/nginx/html

# Copy file tĩnh
COPY ./public ./        
COPY ./src ./src        

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
